"""empty message

Revision ID: 1233848fb83e
Revises: 
Create Date: 2023-09-16 14:55:41.304046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1233848fb83e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth', sa.String(length=255), nullable=True, comment='出生年份'))
        batch_op.alter_column('birthday',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               comment='出生日期',
               existing_comment='出生年份',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.alter_column('birthday',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               comment='出生年份',
               existing_comment='出生日期',
               existing_nullable=True)
        batch_op.drop_column('birth')

    # ### end Alembic commands ###
