"""empty message

Revision ID: 2c29f0d96e75
Revises: 30708d4847be
Create Date: 2023-09-15 00:22:00.213452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c29f0d96e75'
down_revision = '30708d4847be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False, comment='履历信息id'),
    sa.Column('target', sa.String(length=255), nullable=False, comment='目标人物'),
    sa.Column('province', sa.String(length=255), nullable=True, comment='所在省份'),
    sa.Column('local', sa.DateTime(), nullable=True, comment='所在县市'),
    sa.Column('govpos', sa.String(length=255), nullable=True, comment='职务'),
    sa.Column('domains', sa.String(length=255), nullable=True, comment='领域'),
    sa.Column('time', sa.Integer(), nullable=True, comment='起始年份'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='持续时间（年）'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('basic_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['basic_info_id'], ['basic_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume')
    # ### end Alembic commands ###
