"""empty message

Revision ID: 32486850b5c5
Revises: e818dcf0ab66
Create Date: 2023-11-02 22:59:10.262332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32486850b5c5'
down_revision = 'e818dcf0ab66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=255), nullable=True, comment='头像'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.drop_column('profile_photo')

    # ### end Alembic commands ###
