"""empty message

Revision ID: 41f63c4aee9d
Revises: 744083cc5c66
Create Date: 2023-10-09 23:46:22.897639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f63c4aee9d'
down_revision = '744083cc5c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=255), nullable=True, comment='编号'))
        batch_op.create_unique_constraint(None, ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
