"""empty message

Revision ID: 89d9301cb0f6
Revises: 326bb1183aef
Create Date: 2023-09-07 00:14:22.000200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89d9301cb0f6'
down_revision = '326bb1183aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='基础信息id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               comment='姓名',
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=255),
               comment='性别',
               existing_nullable=True)
        batch_op.alter_column('ethnic',
               existing_type=mysql.VARCHAR(length=255),
               comment='民族',
               existing_nullable=True)
        batch_op.alter_column('ancestral_province',
               existing_type=mysql.VARCHAR(length=255),
               comment='籍贯省份',
               existing_nullable=True)
        batch_op.alter_column('ancestral_local',
               existing_type=mysql.VARCHAR(length=255),
               comment='籍贯县市',
               existing_nullable=True)
        batch_op.alter_column('birthplace_province',
               existing_type=mysql.VARCHAR(length=255),
               comment='出生省份',
               existing_nullable=True)
        batch_op.alter_column('birthplace_local',
               existing_type=mysql.VARCHAR(length=255),
               comment='出生县市',
               existing_nullable=True)
        batch_op.alter_column('birthday',
               existing_type=mysql.DATETIME(),
               comment='出生年份',
               existing_nullable=True)
        batch_op.alter_column('participate',
               existing_type=mysql.INTEGER(),
               comment='入党年份',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.alter_column('participate',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='入党年份',
               existing_nullable=True)
        batch_op.alter_column('birthday',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='出生年份',
               existing_nullable=True)
        batch_op.alter_column('birthplace_local',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='出生县市',
               existing_nullable=True)
        batch_op.alter_column('birthplace_province',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='出生省份',
               existing_nullable=True)
        batch_op.alter_column('ancestral_local',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='籍贯县市',
               existing_nullable=True)
        batch_op.alter_column('ancestral_province',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='籍贯省份',
               existing_nullable=True)
        batch_op.alter_column('ethnic',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='民族',
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='性别',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='姓名',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='基础信息id',
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
