"""empty message

Revision ID: c34335fc4337
Revises: 9b11bfaee3f6
Create Date: 2023-09-06 23:36:57.034300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34335fc4337'
down_revision = '9b11bfaee3f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ethnic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.drop_column('ethnic')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
