"""empty message

Revision ID: d5b117466d04
Revises: 5539f32a030c
Create Date: 2023-09-09 21:37:26.662064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5b117466d04'
down_revision = '5539f32a030c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edu_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delete_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='教育信息id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('level',
               existing_type=mysql.VARCHAR(length=255),
               comment='教育等级',
               existing_nullable=False)
        batch_op.alter_column('school_province',
               existing_type=mysql.VARCHAR(length=255),
               comment='学校所在省',
               existing_nullable=True)
        batch_op.alter_column('school_local',
               existing_type=mysql.VARCHAR(length=255),
               comment='学校所在县市',
               existing_nullable=True)
        batch_op.alter_column('school_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='学校名称',
               existing_nullable=False)
        batch_op.alter_column('enrollment',
               existing_type=mysql.DATETIME(),
               comment='入学时间',
               existing_nullable=True)
        batch_op.alter_column('isnational',
               existing_type=mysql.VARCHAR(length=255),
               comment='是否是国内高校',
               existing_nullable=True)
        batch_op.alter_column('remarks',
               existing_type=mysql.VARCHAR(length=255),
               comment='备注',
               existing_nullable=True)

    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delete_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delete_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('delete_time')
        batch_op.drop_column('update_time')
        batch_op.drop_column('create_time')

    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.drop_column('delete_time')
        batch_op.drop_column('update_time')
        batch_op.drop_column('create_time')

    with op.batch_alter_table('edu_info', schema=None) as batch_op:
        batch_op.alter_column('remarks',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
        batch_op.alter_column('isnational',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='是否是国内高校',
               existing_nullable=True)
        batch_op.alter_column('enrollment',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='入学时间',
               existing_nullable=True)
        batch_op.alter_column('school_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='学校名称',
               existing_nullable=False)
        batch_op.alter_column('school_local',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='学校所在县市',
               existing_nullable=True)
        batch_op.alter_column('school_province',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='学校所在省',
               existing_nullable=True)
        batch_op.alter_column('level',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='教育等级',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='教育信息id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('delete_time')
        batch_op.drop_column('update_time')
        batch_op.drop_column('create_time')

    # ### end Alembic commands ###
