"""empty message

Revision ID: e818dcf0ab66
Revises: 927d2bfc6d63
Create Date: 2023-10-21 18:09:48.380290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e818dcf0ab66'
down_revision = '927d2bfc6d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ideology',
    sa.Column('id', sa.Integer(), nullable=False, comment='意识形态id'),
    sa.Column('orientation', sa.Enum('激进', '保守', '不作为'), nullable=True, comment='政治倾向'),
    sa.Column('economic_view', sa.Enum('国家资本主义', '自由经济', '斯大林模式'), nullable=True, comment='经济观点'),
    sa.Column('nation_view', sa.Enum('汉族主义', '完整公民权', '中华民族'), nullable=True, comment='民族观点'),
    sa.Column('war_view', sa.Enum('沙文主义', '和平主义'), nullable=True, comment='战争观点'),
    sa.Column('political_view', sa.Enum('精英政治', '民粹主义'), nullable=True, comment='政治观点'),
    sa.Column('ideology_cpc', sa.Enum('毛泽东思想', '中国特色社会主义', '新时代思想'), nullable=True, comment='中共意识形态'),
    sa.Column('family_background', sa.Enum('贵族', '平民'), nullable=True, comment='家庭出身'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('basic_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['basic_info_id'], ['basic_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ideology')
    # ### end Alembic commands ###
