"""empty message

Revision ID: f3c4c27716d6
Revises: 822f0429678c
Create Date: 2023-12-26 00:20:27.247408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c4c27716d6'
down_revision = '822f0429678c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('general_min_age', sa.String(length=255), nullable=True, comment='一般年龄下限'))
        batch_op.add_column(sa.Column('general_max_age', sa.String(length=255), nullable=True, comment='一般年龄上限'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_column('general_max_age')
        batch_op.drop_column('general_min_age')

    # ### end Alembic commands ###
